### PR TITLE
Add JSF plugin, for LifeCycles and Phases

### PR DESCRIPTION
**Pull request by ajdevries**

### CODE REVIEW

**Comment by trask** [comment]
Hi, what do you think about having just this one trace entry for the JSF Plugin?

```
{
  "className": "com.sun.faces.lifecycle.RenderResponsePhase",
  "methodName": "execute",
  "methodParameterTypes": [
    "javax.faces.context.FacesContext"
  ],
  "captureKind": "trace-entry",
  "timerName": "jsf render",
  "traceEntryMessageTemplate": "jsf render: {{0.viewRoot.viewId}}"
}
```

I like that this would be consistent with the single "jsp render" trace entry from the JSP plugin.

Thanks,
Trask

**Comment by ajdevries** [comment]
Hi,

That's an interesting approach, and much less code ;-) This is interesting for view rendering, but the other instrumentations I wrote are also use full for measuring the controllers. It is possible that there are performance bottlenecks in the JSF controller (Beans) code. So how to measure them?

I tested the above code, and it works great in the test app I'm using.

**Comment by trask** [comment]
I went ahead and merged the view rendering portion.  Yeah, I didn't understand the other instrumentation was for controllers.  I'll have another look at that.  Thanks.

**Comment by trask** [comment]
This seems good for capturing controller actions:
```
{
  "className": "com.sun.faces.application.ActionListenerImpl",
  "methodName": "processAction",
  "methodParameterTypes": [
    "javax.faces.event.ActionEvent"
  ],
  "captureKind": "trace-entry",
  "timerName": "jsf action",
  "traceEntryMessageTemplate": "jsf action: {{0.component.id}}"
}
```
Let me know what you think.  Thanks.

**Pull request closed without merging**
