### PR TITLE
Add Spring plugin

### PR DESCRIPTION
**Pull request by ajdevries**
Maybe a good idea to get this plugin in the glowroot master branch

### CODE REVIEW

**Comment by trask** [comment]
Sorry for the delay, I want to test this out a bit on a real application, may be a few days.

**Comment by ajdevries** [comment]
No problem. Happy that you investigate and take things seriously. If I can help let me know. I tested this with a simple Todo Spring MVC app and a load test in gatling.

**Comment by trask** [comment]
I've been thinking a few days about transaction naming.  I think URL-based transaction names are a better default for operations folk, primarily because they can be easily mapped to other monitoring systems, e.g. network monitoring, browser end user monitoring, etc.  A secondary benefit is that URLs tend to be more stable, e.g. don't change due to code refactoring.

The main problem with the existing transaction naming provided by the servlet plugin is that the transaction name is set to the full URL, which doesn't make sense for applications with parameterized URLs, since it doesn't group together similar transactions.

For Spring-based applications, if we set the transaction name to the URL _mapping_, it gives us both a URL-based transaction name, as well as a transaction name that maps one-to-one with Spring controller actions.

For a specific example, the controller below would have transaction name `/hello/echo/{messageText}`, or the shorter `/hello/echo/*` (which I think I prefer).

```
    @Controller
    @RequestMapping("hello")
    public static class HelloController {
        @RequestMapping("echo/{messageText}")
        public @ResponseBody String echo(...) {
            ...
        }
    }
```

I committed your original PR b5aa8b16c9d7fa26d198b52c793ee18ef0274708, plus I committed the transaction naming change 0c5c39e1c7148f3ffe40493578a08be5890a9113.  Please have a look and let me know if you are ok with this change.  I also committed a JAX-RS plugin fb662dc87156b635dea497755fb0e319fb75d457 to show how the same transaction naming approach applies more generally than just Spring.

**Comment by ajdevries** [comment]
This all looks very goods. Thanks for merging and thanks for the upgrade of the transaction naming. Knowing what your endpoints / slow transactions are doing is great. And aggregating them around code / controller logic is a good step.

I'm also using glowroot with a Grails applications. Spring MVC with a Groovy sauce and I need to figure out how transaction naming is working there. Another request is support for Apache CXF, I'm looking into that too.

The collector I'm using now is more code centric instead of URL centric. But this strongly depends on the framework you are using. In Rails URLs represent controller#action methods more often. So I'm not entirely sure this is the best approach, but for now this is okay. And once again I'm very happy having this plugin in the glowroot master branch.

**Comment by ajdevries** [comment]
I'm debugging this new transaction naming and think it got an issues. What I can see now is a servletpath and a controller path as transaction name, i.e. `user/todos/user/todos`. I don't think that's right. Besides that I'm using the `Controller.action` name for transactions. I could get them from the trace entry but for now I placed back the old code. That works with the current collector. Later on I can switch to the new format.

**Comment by trask** [comment]
Thanks for catching that. I've fixed the transaction naming issue, and pushed a few more changes, including Spring and JAX-RS plugin config settings to use "alternate transaction naming", which is the `Class#method` transaction naming style.

**Pull request closed without merging**
