### PR TITLE
Add support for Cassandra ssl and port options in central collector

### PR DESCRIPTION
**Pull request by babatsai**
This PR the Central Collector to be flexible in when connecting to a cassandra cluster. More specifically, the application can to connect to Azure Cosmos DB Cassandra API using port = 10350 and ssl = true.

### CODE REVIEW

**Comment by trask** [comment]
Closing and re-opening to try to trigger Travis CI build (somehow it got turned off for PRs)

**Comment by trask** [comment]
Thanks!

**Comment by ionutursuleanu** [comment]
AWS just announced [Amazon Managed Apache Cassandra Service (MCS)](https://aws.amazon.com/blogs/aws/new-amazon-managed-apache-cassandra-service-mcs/).

> Amazon MCS only accepts secure connections using TLS.

👍

**Comment by ponnamvivek** [comment]
hi..!

Were you able to auto-create glowroot schema/tables in cosmos DB..? what changes are required for schema /tables creation..? Are you using any GUI tools to query cosmos DB?

Thanks in advance..!

**Pull request merged**
